"""
Analysis schemas for the Kano Model agent.

Defines input contract (KanoInput), enriched feature output with Berger
coefficients, roadmap structure, and the final KanoOutput.

Scientific basis:
- Berger, C. et al. (1993). Kano's methods for understanding customer-defined
  quality. Center for Quality Management Journal, 2(4), 3-35.
  CS = (Attractive + One-dimensional) / (Attractive + One-dimensional + Must-be + Indifferent)
  DS = -1 * (One-dimensional + Must-be) / (Attractive + One-dimensional + Must-be + Indifferent)
- Matzler & Hinterhuber (1998). Technovation, 18(1). DOI: 10.1016/S0166-4972(97)00020-0
"""
from __future__ import annotations

from pydantic import BaseModel, field_validator

from classification.schema import ClassifiedFeature


class Feature(BaseModel):
    """A product feature provided as input."""
    id: str
    name: str
    description: str


class KanoInput(BaseModel):
    """Input contract for the Kano Model agent."""
    product_name: str
    product_description: str
    target_market: str | None = None
    features: list[Feature]


class ClassifiedFeatureWithCoefficients(ClassifiedFeature):
    """
    A classified feature enriched with Berger satisfaction coefficients.

    satisfaction_coefficient (CS): 0.0-1.0
        How much implementing this feature increases satisfaction.
        High for Attractive features, low for Must-be.

    dissatisfaction_coefficient (DS): -1.0-0.0
        How much NOT implementing this feature causes dissatisfaction.
        High magnitude for Must-be, low for Attractive.
    """
    satisfaction_coefficient: float
    dissatisfaction_coefficient: float

    @field_validator("satisfaction_coefficient")
    @classmethod
    def validate_cs(cls, v: float) -> float:
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"satisfaction_coefficient must be in [0.0, 1.0], got {v}")
        return round(v, 3)

    @field_validator("dissatisfaction_coefficient")
    @classmethod
    def validate_ds(cls, v: float) -> float:
        if not -1.0 <= v <= 0.0:
            raise ValueError(f"dissatisfaction_coefficient must be in [-1.0, 0.0], got {v}")
        return round(v, 3)


class Roadmap(BaseModel):
    """
    4-quadrant prioritization roadmap derived from Kano classifications.

    immediate_priorities: Must-be features — implement first or risk losing customers.
    performance_investments: One-dimensional features — improve for satisfaction gains.
    innovation_bets: Attractive features — differentiation opportunities.
    deprioritize: Indifferent/Reverse features — low ROI, defer or remove.
    """
    immediate_priorities: list[str]
    performance_investments: list[str]
    innovation_bets: list[str]
    deprioritize: list[str]


class KanoOutput(BaseModel):
    """Full output contract for the Kano Model agent."""
    product_name: str
    features: list[ClassifiedFeatureWithCoefficients]
    summary: dict[str, int]             # e.g. {"Must-be": 3, "Attractive": 4, ...}
    roadmap: Roadmap
    strategic_narrative: str
    html_report: str | None = None      # Injected by renderer, never generated by LLM
